INSERT INTO
    emn.mst_item
    (
        mst_item_id,
        item_number,
        item_name,
        abbreviation,
        mst_item_category_id,
        mst_item_status_id,
        mst_item_unit_id,
        bss_machine_list_id,
        mst_warehouse_id,
        lower_limit_inventory_qty,
        safety_inventory_qty,
        upper_limit_inventory_qty,
        min_lot_qty,
        max_lot_qty,
        unit_price,
        validity_days,
        mst_client_id,
        mst_delivery_destination_id,
        bss_end_user_list_id,
        rank,
        remark,
        table_information_id
    )
    VALUES
    (
        :mst_item_id,
        :item_number,
        :item_name,
        :abbreviation,
        :mst_item_category_id,
        :mst_item_status_id,
        :mst_item_unit_id,
        :bss_machine_list_id,
        :mst_warehouse_id,
        :lower_limit_inventory_qty,
        :safety_inventory_qty,
        :upper_limit_inventory_qty,
        :min_lot_qty,
        :max_lot_qty,
        :unit_price,
        :validity_days,
        :mst_client_id,
        :mst_delivery_destination_id,
        :bss_end_user_list_id,
        :rank,
        :remark,
        :table_information_id
    )
;
